Repository Merge-co/OIL-JANG_BE, pull requests merged in 2023-11, with the labels that each got.

#11 신고기능 TDD진행
  .gitignore
  build.gradle
  src/main/java/com/mergeco/olijang/common/dummy
  src/main/java/com/mergeco/olijang/config/BeanConfiguration.java
  src/main/java/com/mergeco/olijang/config/dummy1
  src/main/java/com/mergeco/olijang/report/controller/ReportController.java
  src/main/java/com/mergeco/olijang/report/entity/Report.java
  src/main/java/com/mergeco/olijang/report/entity/ReportCategory.java
  src/main/java/com/mergeco/olijang/report/model/dto/ReportCategoryDTO.java
  src/main/java/com/mergeco/olijang/report/model/dto/ReportDTO.java
  src/main/java/com/mergeco/olijang/report/repository/ReportRepository.java
  src/main/java/com/mergeco/olijang/report/service/ReportService.java
  src/main/resources/application.yml
  src/test/java/com/mergeco/olijang/report/ReportTests.java
  src/test/java/com/mergeco/olijang/report/dummy
Labels: CRUD

#14 20231103 로그인 및 회원가입 Entity 추가
  build.gradle
  src/main/java/com/mergeco/olijang/user/entity/EnrollType.java
  src/main/java/com/mergeco/olijang/user/entity/User.java
  src/main/java/com/mergeco/olijang/user/model/dto/UserDTO.java
  src/main/java/com/mergeco/olijang/user/model/service/UserService.java
  src/main/java/com/mergeco/olijang/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: enhancement, entity

#15 [BE][FEATURE]신고기능 TDD
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/entity/Report.java
  src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
  src/main/java/com/mergeco/oiljang/report/repository/ReportCategoryRepository.java
  src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
  src/main/resources/application.yml
  src/test/java/com/mergeco/oiljang/product1/ProductControllerTests.java
  src/test/java/com/mergeco/oiljang/report/ReportTests.java
Labels: CRUD

#16 [BE][FEATURE]Message Insert TDD
  src/main/java/com/mergeco/oiljang/inquery/dto/InqDTO.java
  src/main/java/com/mergeco/oiljang/inquery/dto/InqUserDTO.java
  src/main/java/com/mergeco/oiljang/inquery/entity/InqCategory.java
  src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
  src/main/java/com/mergeco/oiljang/inquery/repository/InqCategoryRepository.java
  src/main/java/com/mergeco/oiljang/inquery/repository/InqRepository.java
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgDeleteDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgProInfoDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgUserDTO.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/entity/MsgDelete.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgDeleteRepository.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/inquery/InquiryTests.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: message, insert

#19 [BE][FEATURE] JWT 설정 추가
  build.gradle
  src/main/java/com/mergeco/oiljang/auth/config/WebConfig.java
  src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
  src/main/java/com/mergeco/oiljang/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/mergeco/oiljang/auth/interceptor/JwtTokenInterceptor.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/JoinDTO.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/LoginDTO.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/dummy
  src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
  src/main/java/com/mergeco/oiljang/common/AuthConstants.java
  src/main/java/com/mergeco/oiljang/common/UserRole.java
  src/main/java/com/mergeco/oiljang/common/utils/ConvertUtil.java
  src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
  src/main/java/com/mergeco/oiljang/user/controller/UserController.java
  src/main/java/com/mergeco/oiljang/user/controller/dummy
  src/main/java/com/mergeco/oiljang/user/entity/EnrollType.java
  src/main/java/com/mergeco/oiljang/user/entity/User.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: enhancement, JWT, CRUD, entity, insert

#24 [BE][FEATURE] 회원가입 프로필 등록 수정
  build.gradle
  src/main/java/com/mergeco/oiljang/auth/config/WebConfig.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
  src/main/java/com/mergeco/oiljang/config/FileUploadConfig.java
  src/main/java/com/mergeco/oiljang/user/controller/UserController.java
  src/main/java/com/mergeco/oiljang/user/entity/User.java
  src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/main/java/com/mergeco/oiljang/user/repository/UserProfileRepository.java
  src/main/resources/application.yml
  src/test/java/com/mergeco/oiljang/user/UserTests.java
Labels: jpa, CRUD, USER, entity, TDD

#38 [BE][FEATURE]쪽지 상세 조회까지 성공, sender receiver 조건 조회 구현중
  src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgInsertDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgProUserInfoDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgReceiverDTO.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgUserDTO.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: jpa, message, CRUD, TDD, select

#40 [BE][FEATURE] swagger, webSecurityConfig관련 문제
  src/main/java/com/mergeco/oiljang/product/controller/FileUploadController.java
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/test/java/com/mergeco/oiljang/product/FileUploadControllerTest.java
  src/test/java/com/mergeco/oiljang/product/ProductTests.java
Labels: jpa, CRUD, product, wishList, select

#39 [BE][FEATURE]쪽지 상세 조회까지 성공, sender receiver 조건 조회 구현중
  src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/entity/MsgDeleteInfo.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: message, CRUD, TDD, select

#43 :bug: [BE][FEATURE] 신고 CRUD Swagger
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/dto/ReportCategoryDTO.java
  src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
  src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
  src/test/java/com/mergeco/oiljang/report/ReportTests.java
Labels: jpa, CRUD

#42 [BE][FEATURE]상품 이미지 업로드 DB 접속 완료 & 판매목록 조회
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/dto/SellingListDTO.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
Labels: bug, jpa, CRUD, product, select

#44 [BE][FEATURE] user_code 관련된 부분 int로 수정하기
  sql/oilJangSql.sql
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductDTO.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductDetailDTO.java
  src/main/java/com/mergeco/oiljang/product/entity/Product.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/main/java/com/mergeco/oiljang/wishlist/controller/WishListController.java
  src/main/java/com/mergeco/oiljang/wishlist/dto/WishListDTO.java
  src/main/java/com/mergeco/oiljang/wishlist/entity/WishList.java
  src/main/java/com/mergeco/oiljang/wishlist/service/WishListService.java
  src/test/java/com/mergeco/oiljang/product/ProductTests.java
  src/test/java/com/mergeco/oiljang/wishlist/WishListTests.java
Labels: jpa, product, wishList, entity

#46 [BE][FEATURE]쪽지리스트 조회 SENDER/RECEIVER 조건 구현(좀 더 손봐야함)
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: jpa, message, CRUD, TDD, select

#74 [BE][Feature] 로그인 기능 수정
  src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/filter/HeaderFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/TokenProvider.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/TokenDTO.java
  src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
  src/main/java/com/mergeco/oiljang/common/restApi/LoginMessage.java
  src/main/java/com/mergeco/oiljang/common/restApi/ResponseMessage.java
  src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
  src/main/java/com/mergeco/oiljang/user/controller/UserController.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
  src/test/java/com/mergeco/oiljang/user/UserTests.java
Labels: FEATURE🎉

#73 [BE][FEATURE]상품 삭제 진행중
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/test/java/com/mergeco/oiljang/product/ProductTests.java
Labels: FEATURE🎉

#72 :technologist: [BE][FEATURE] 신고기능 CRUD 완료
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
  src/main/java/com/mergeco/oiljang/report/entity/Report.java
  src/main/java/com/mergeco/oiljang/report/entity/ReportCategory.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
Labels: FEATURE🎉

#71 [BE][FEATURE] 상품, 관심 목록 관련 TDD 수정
  sql/oilJangSql.sql
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/test/java/com/mergeco/oiljang/product/ProductTests.java
  src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
  src/test/java/com/mergeco/oiljang/product/service/ProductServiceTests.java
  src/test/java/com/mergeco/oiljang/wishlist/WishListTests.java
  src/test/java/com/mergeco/oiljang/wishlist/controller/WishListControllerTests.java
  src/test/java/com/mergeco/oiljang/wishlist/service/WishListServiceTests.java
Labels: FEATURE🎉

#70 [BE][FEATURE] 쪽지 수정 기능 구현중
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgDTO.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: FEATURE🎉

#75 [BE][Feature] 상품 수정 완료
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductDTO.java
  src/main/java/com/mergeco/oiljang/product/entity/Product.java
  src/main/java/com/mergeco/oiljang/product/repository/ProductRepository.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
Labels: FEATURE🎉

#76 [BE][FEATURE] 로그인 기능 수정
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/common/UserRole.java
  src/main/java/com/mergeco/oiljang/common/exception/DuplicateNicknameException.java
  src/main/java/com/mergeco/oiljang/common/exception/InvalidPasswordException.java
  src/main/java/com/mergeco/oiljang/common/exception/UserNotFoundException.java
  src/main/java/com/mergeco/oiljang/user/controller/UserController.java
  src/main/java/com/mergeco/oiljang/user/model/dto/UpdateUserDTO.java
  src/main/java/com/mergeco/oiljang/user/model/dto/UserDTO.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
  src/test/java/com/mergeco/oiljang/auth/AuthTests.java
  src/test/java/com/mergeco/oiljang/auth/dummy
  src/test/java/com/mergeco/oiljang/user/UserTests.java
Labels: BUG🐛, FEATURE🎉

#77 :bug: [BE][FEATURE] 신고기능 전체조회 변경
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
  src/test/java/com/mergeco/oiljang/report/ReportTests.java
Labels: BUG🐛

#78 [BE][FEATURE] 쪽지 수정기능 수정중
  src/main/java/com/mergeco/oiljang/inquery/controller/InqController.java
  src/main/java/com/mergeco/oiljang/inquery/dto/InqCategoryDTO.java
  src/main/java/com/mergeco/oiljang/inquery/dto/InqDTO.java
  src/main/java/com/mergeco/oiljang/inquery/dto/InqInsertDTO.java
  src/main/java/com/mergeco/oiljang/inquery/dto/InqUserDTO.java
  src/main/java/com/mergeco/oiljang/inquery/entity/Inquiry.java
  src/main/java/com/mergeco/oiljang/inquery/service/InqService.java
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/inquery/InquiryTests.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: BUG🐛

#80 [BE][FEATURE] 상품 조회 관련 매개변수와 보내주는 결과 수정
  src/main/java/com/mergeco/oiljang/common/paging/JpqlPagingButton.java
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductListDTO.java
  src/main/java/com/mergeco/oiljang/product/entity/Product.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/test/java/com/mergeco/oiljang/product/service/ProductServiceTests.java
Labels: FEATURE🎉

#81 [BE][Feature] 회원가입 기능 수정
  src/main/java/com/mergeco/oiljang/auth/config/JwtSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/filter/JwtFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/mergeco/oiljang/auth/handler/JwtAccessDeniedHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/mergeco/oiljang/auth/handler/TokenProvider.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
  src/main/java/com/mergeco/oiljang/common/AuthConstants.java
  src/main/java/com/mergeco/oiljang/common/UserRole.java
  src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
  src/main/java/com/mergeco/oiljang/user/controller/UserController.java
  src/main/java/com/mergeco/oiljang/user/entity/User.java
  src/main/java/com/mergeco/oiljang/user/entity/UserProfile.java
  src/main/java/com/mergeco/oiljang/user/model/dto/UserDTO.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/test/java/com/mergeco/oiljang/auth/AuthTests.java
  src/test/java/com/mergeco/oiljang/user/UserTests.java
Labels: BUG🐛, FEATURE🎉

#79 [BE][FEATURE]1:1문의 수정
  src/main/java/com/mergeco/oiljang/inquery/controller/InqController.java
  src/main/java/com/mergeco/oiljang/inquery/repository/InqCategoryRepository.java
  src/main/java/com/mergeco/oiljang/inquery/repository/InqRepository.java
  src/main/java/com/mergeco/oiljang/inquery/service/InqService.java
  src/main/java/com/mergeco/oiljang/inquiry/controller/InqController.java
  src/main/java/com/mergeco/oiljang/inquiry/dto/InqCategoryDTO.java
  src/main/java/com/mergeco/oiljang/inquiry/dto/InqDTO.java
  src/main/java/com/mergeco/oiljang/inquiry/dto/InqInsertDTO.java
  src/main/java/com/mergeco/oiljang/inquiry/dto/InqSelectDetailDTO.java
  src/main/java/com/mergeco/oiljang/inquiry/dto/InqSelectListDTO.java
  src/main/java/com/mergeco/oiljang/inquiry/entity/InqCategory.java
  src/main/java/com/mergeco/oiljang/inquiry/entity/Inquiry.java
  src/main/java/com/mergeco/oiljang/inquiry/repository/InqCategoryRepository.java
  src/main/java/com/mergeco/oiljang/inquiry/repository/InqRepository.java
  src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/entity/MsgDeleteInfo.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/inquery/InquiryTests.java
  src/test/java/com/mergeco/oiljang/inquiry/InquiryTests.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: FEATURE🎉

#82 [BE][FEATURE]1:1문의 삭제 기능 완료
  src/main/java/com/mergeco/oiljang/inquiry/controller/InqController.java
  src/main/java/com/mergeco/oiljang/inquiry/service/InqService.java
  src/test/java/com/mergeco/oiljang/inquiry/InquiryTests.java
Labels: FEATURE🎉

#87 [BE][BUG]쪽지 키워드 조회 수정
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
Labels: BUG🐛

#89 [BE][Feature] 로그인 기능
  src/main/java/com/mergeco/oiljang/auth/config/OAuth2Config.java
  src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/filter/JwtFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/mergeco/oiljang/auth/handler/OAuth2LoginHandler.java
  src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/OAuth2LoginDTO.java
  src/main/java/com/mergeco/oiljang/auth/model/dto/OAuth2LoginResponseDTO.java
  src/main/java/com/mergeco/oiljang/auth/model/service/DetailsService.java
  src/main/java/com/mergeco/oiljang/auth/model/service/OAuth2DetailsService.java
  src/main/java/com/mergeco/oiljang/common/utils/TokenUtils.java
  src/main/java/com/mergeco/oiljang/user/controller/OAuth2Controller.java
  src/main/java/com/mergeco/oiljang/user/model/service/OAuth2Service.java
  src/main/java/com/mergeco/oiljang/user/repository/CustomOAuth2AuthorizationRequestRepository.java
  src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: FEATURE🎉

#91 [BE][Feature] 상품 조회시 백엔드에서 보내주는 데이터 변경
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductListDTO.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/main/java/com/mergeco/oiljang/wishlist/dto/WishListInfoDTO.java
  src/main/java/com/mergeco/oiljang/wishlist/service/WishListService.java
  src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
Labels: FEATURE🎉

#92 :memo: [BE][FEATURE]신고기능 Search 기능 추가
  src/main/java/com/mergeco/oiljang/config/BeanConfiguration.java
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/dto/ReportDTO.java
  src/main/java/com/mergeco/oiljang/report/entity/Report.java
  src/main/java/com/mergeco/oiljang/report/repository/ReportRepository.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
  src/test/java/com/mergeco/oiljang/product/service/ProductServiceTests.java
  src/test/java/com/mergeco/oiljang/report/ReportTests.java
Labels: FEATURE🎉

#93 [BE][FEATURE]쪽지 리스트 조회 DTO수정
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgListDTO.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
Labels: BUG🐛

#94 20231122-product-001 관심 목록 찜 제대로 안 되는 거 수정했습니다.
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
Labels: FEATURE🎉

#95 [BE][Feature] 로그인
  src/main/java/com/mergeco/oiljang/auth/config/JwtSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/config/OAuth2Config.java
  src/main/java/com/mergeco/oiljang/auth/config/WebSecurityConfig.java
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/mergeco/oiljang/auth/model/DetailsUser.java
  src/main/java/com/mergeco/oiljang/auth/model/service/OAuth2DetailsService.java
  src/main/java/com/mergeco/oiljang/user/controller/OAuth2Controller.java
  src/main/java/com/mergeco/oiljang/user/model/service/OAuth2Service.java
  src/main/java/com/mergeco/oiljang/user/model/service/UserService.java
  src/main/java/com/mergeco/oiljang/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: BUG🐛, FEATURE🎉

#97 [BE][BUG]쪽지 등록 관련 DTO 필드 수정
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgProUserInfoDTO.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: BUG🐛

#100 :ambulance: [BE][FEATURE]신고기능 Search 구현(완) (#96)
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
  src/main/java/com/mergeco/oiljang/report/dto/ReportsDTO.java
  src/main/java/com/mergeco/oiljang/report/service/ReportService.java
Labels: FEATURE🎉

#101 :technologist: [BE][FEATURE]신고기능 페이징 처리
  src/main/java/com/mergeco/oiljang/report/controller/ReportController.java
Labels: FEATURE🎉

#103 [BE][BUG] 상품등록 완료
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
Labels: BUG🐛

#108 [BE][Feature] 로그인 수정
  src/main/java/com/mergeco/oiljang/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/mergeco/oiljang/auth/handler/OAuth2SuccessHandler.java
Labels: BUG🐛, FEATURE🎉

#112 [BE][BUG]상품삭제 완료
  src/main/java/com/mergeco/oiljang/product/entity/Product.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
Labels: BUG🐛

#110 [BE][FEATURE]쪽지 검색 기능 관련 컨트롤러 변경
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/repository/MsgDeleteRepository.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: FEATURE🎉

#117 [BE][BUG]쪽지 조회 관련 쿼리문 수정
  src/main/java/com/mergeco/oiljang/message/controller/MsgController.java
  src/main/java/com/mergeco/oiljang/message/dto/MsgReceiverDTO.java
  src/main/java/com/mergeco/oiljang/message/entity/Message.java
  src/main/java/com/mergeco/oiljang/message/service/MsgService.java
  src/main/java/com/mergeco/oiljang/product/dto/ProductDetailDTO.java
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
  src/test/java/com/mergeco/oiljang/message/MessageTests.java
Labels: BUG🐛

#115 [BE][BUG]상품수정 완료
  src/main/java/com/mergeco/oiljang/product/service/ProductService.java
Labels: BUG🐛

#114 [BE][Feature] MyCalendar 관련 도메인 추가 및 파일 추가
  src/main/java/com/mergeco/oiljang/myCalendar/controller/MyCalendarController.java
  src/main/java/com/mergeco/oiljang/myCalendar/dto/MyCalendarDTO.java
  src/main/java/com/mergeco/oiljang/myCalendar/entity/MyCalendar.java
  src/main/java/com/mergeco/oiljang/myCalendar/repository/MyCalendarRepository.java
  src/main/java/com/mergeco/oiljang/myCalendar/service/MyCalendarService.java
  src/main/java/com/mergeco/oiljang/product/controller/ProductController.java
  src/test/java/com/mergeco/oiljang/myCalendar/controller/MyCalendarControllerTests.java
  src/test/java/com/mergeco/oiljang/myCalendar/service/MyCalendarServiceTests.java
  src/test/java/com/mergeco/oiljang/product/controller/ProductControllerTests.java
Labels: FEATURE🎉
